pipeline {
    agent any
    
    environment {
        // Define server credentials - replace with your values
        LINUX_SERVER = '192.168.118.128'
        LINUX_USER = 'server1'
    }
    
    stages {
        stage('Run Date Command') {
            steps {
                // Using SSH to connect and execute command
                sshagent(['linux-server-credentials']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${LINUX_USER}@${LINUX_SERVER} 'date'
                    """
                }
            }
        }
    }
}