pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo 'Building the project...'
        echo 'Finalizing the project...'
      }
    }
    stage('Test') {
      steps {
        echo 'Running tests...'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying application...'
      }
    }
  }
}
